import React from "react";
// import { Provider } from "react-redux";
import "bootstrap/dist/css/bootstrap.min.css";
import "font-awesome/css/font-awesome.css";
import "bootstrap-social/bootstrap-social.css";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
// import store from './redux/store';
ReactDOM.render(<App />, document.getElementById("root"));
