export const initialValues = {
    firstName: 'Test',
    lastName: 'Name',
    email: 'test@test.com',
    dob: "1999-11-11",
    gender: 'Male',
    fatherName: 'TEST',
    motherName: 'TESTING',
    contact: '0123456789',
    class: '7',
    year: '',
    schoolOrUniv: 'School',
    board: 'CBSE',
    houseNumber: '123',
    addressLine1: 'Hussainpur,Anandapur',
    addressLine2: '',
    landmark: 'xyzzzzzzz',
    district: 'Manpur',
    city: 'Gaya',
    pincode: '700107',
    country: 'India',
    facebookLink: 'http://www.facebook.com/',
    linkedinLink: 'http://www.linkdin.com/',
    githubLink: '',
};
